from enum import Enum


class Play:

    def __init__(self):
        self.minute = ""
        self.definition = ""
        self.coordinates = []


class PlayType(Enum):

    SUBSTITUTION_IN = "SUBSTITUTION_IN"
    SUBSTITUTION_OUT = "SUBSTITUTION_OUT"
    ASSISTS = "ASSISTS"
    STEALS = "STEALS"
    TURNOVERS = "TURNOVERS"
    BLOCKED_SHOTS = "BLOCKED_SHOTS"
    BLOCKS_RECEIVED = "BLOCKS_RECEIVED"
    FOULS_MADE = "FOULS_MADE"
    FOULS_RECEIVED = "FOULS_RECEIVED"
    TWO_ATTEMPTED = "TWO_ATTEMPTED"
    TWO_MADE = "TWO_MADE"
    THREE_ATTEMPTED = "THREE_ATTEMPTED"
    THREE_MADE = "THREE_MADE"
    FREE_THROW_ATTEMPTED = "FREE_THROW_ATTEMPTED"
    FREE_THROW_MADE = "FREE_THROW_MADE"
